version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Dependabot"
    commit-message:
      prefix: "update"
